import os
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
if not OPENROUTER_API_KEY:
    raise ValueError("OPENROUTER_API_KEY not found in .env")

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=OPENROUTER_API_KEY
)

def validate_analysis(article, analysis):
    """
    Validate analysis generated by LLM#1 using LLM#2
    Returns True/False and explanation
    """
    title = article.get("title", "")
    description = article.get("description", "")
    content = article.get("content", "")

    full_text = f"Title: {title}\nDescription: {description}\nContent: {content}"

    prompt = f"""
    You are a professional news analyst.
    Check the analysis of the following article:

    Article:
    {full_text}

    Analysis:
    Gist: {analysis.get('gist')}
    Sentiment: {analysis.get('sentiment')}
    Tone: {analysis.get('tone')}

    Question:
    Is the analysis accurate? If yes, respond with ✅ Correct.
    If no, provide corrections and explanation.
    """

    try:
        response = client.chat.completions.create(
            model="openai/gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}]
        )
        validation = response.choices[0].message.content.strip()
    except Exception as e:
        validation = f"Validation error: {str(e)}"

    return validation
